<a href="https://colab.research.google.com/github/mubinui/NeuralNetworks/blob/main/TwitterDataAnalysisLSTM01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


$$Suicidal Ideation$$
Importing important libraries 

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
# from keras.models import Sequential 
# from keras.layers import Embedding, LSTM, Dense, Dropout
from sklearn.preprocessing import LabelEncoder

import warnings 
warnings.filterwarnings('ignore')
sns.set()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


#Working the Twitter Sentiment Dataset  

In [ ]:
sentiment_data = pd.read_csv('/content/drive/MyDrive/Datasets /Twitter_Data.csv')
sentiment_data=sentiment_data.rename(columns={'clean_text':'message', 'category':'result'})
sentiment_data.head(10)

message  result
0  when modi promised “minimum government maximum...    -1.0
1  talk all the nonsense and continue all the dra...     0.0
2  what did just say vote for modi  welcome bjp t...     1.0
3  asking his supporters prefix chowkidar their n...     1.0
4  answer who among these the most powerful world...     1.0
5           kiya tho refresh maarkefir comment karo      0.0
6  surat women perform yagna seeks divine grace f...     0.0
7  this comes from cabinet which has scholars lik...     0.0
8  with upcoming election india saga going import...     1.0
9                         gandhi was gay does modi       1.0

In [ ]:
#Unzipping the necessary datasets 
sentiment_data.dropna(subset = ["message"], inplace=True)
sentiment_data.dropna(subset=['result'], inplace=True)


<h3> Distribution of the target variables </h3>

In [ ]:
sentiment_data.dropna

<bound method DataFrame.dropna of                                                   message  result
0       when modi promised “minimum government maximum...    -1.0
1       talk all the nonsense and continue all the dra...     0.0
2       what did just say vote for modi  welcome bjp t...     1.0
3       asking his supporters prefix chowkidar their n...     1.0
4       answer who among these the most powerful world...     1.0
...                                                   ...     ...
162975  why these 456 crores paid neerav modi not reco...    -1.0
162976  dear rss terrorist payal gawar what about modi...    -1.0
162977  did you cover her interaction forum where she ...     0.0
162978  there big project came into india modi dream p...     0.0
162979  have you ever listen about like gurukul where ...     1.0

[162969 rows x 2 columns]>

In [ ]:
size = int(sentiment_data.shape[0]*0.01)
sentiment_data = sentiment_data[:size]

<h3> Factoring the sentences into words 

In [ ]:
texts = sentiment_data['message'][0]
print(texts)
print('<--------------------->')
print(word_tokenize(texts))

when modi promised “minimum government maximum governance” expected him begin the difficult job reforming the state why does take years get justice state should and not business and should exit psus and temples
<--------------------->
['when', 'modi', 'promised', '“', 'minimum', 'government', 'maximum', 'governance', '”', 'expected', 'him', 'begin', 'the', 'difficult', 'job', 'reforming', 'the', 'state', 'why', 'does', 'take', 'years', 'get', 'justice', 'state', 'should', 'and', 'not', 'business', 'and', 'should', 'exit', 'psus', 'and', 'temples']


In [ ]:
corpus = []
for text in sentiment_data['message']:
    words = [word.lower() for word in word_tokenize(texts)]
    corpus.append(words)

In [ ]:
num_words = len(corpus)
print(num_words)

1629


<h3><b>Splitting Data to Train(80%) and Test(20%)</b></h3>
In our case Train and Test data already splitted 

In [ ]:
X = sentiment_data['message']
y = sentiment_data['result']

In [ ]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.20, random_state=25)

<h3> Tokenizing the words and padding for equal input dimensions

In [ ]:
train_size = int(X_train.shape[0])
X_train = X_train[:train_size]
y_train = y_train[:train_size]
test_size = int(X_test.shape[0])
X_test = X_test[:test_size]
y_test = X_test[:test_size]

In [ ]:
tokenizer  = Tokenizer(num_words)
tokenizer.fit_on_texts(X_train)
X_train = tokenizer.texts_to_sequences(X_train)
X_train = pad_sequences(X_train, maxlen=128, truncating='post', padding='post')

In [ ]:
X_train[0], len(X_train[0])

(array([ 41, 292,  40,   1, 352, 293,  14,  96,  35,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int32),
 128)

<h3>Test</h3>

In [ ]:
X_test = tokenizer.texts_to_sequences(X_test)
X_test = pad_sequences(X_test, maxlen=128, truncating='post', padding='post')

In [ ]:
X_test[0], len(X_test[0])

(array([   6,    1,  385,   19, 1339,  276,  884, 1224,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0], dtype=int32), 128)

<h3>Shape of my Dataset</h3> 

In [ ]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


(1303, 128) (1303,)
(326, 128) (326,)


<h3> <b>Encoding label</b> </h3>
In this dataset no need to encoding label as they are already binary .

In [ ]:
lab_enc  = LabelEncoder()
y_train = lab_enc.fit_transform(y_train)
y_test = lab_enc. fit_transform(y_test)
y_train[:100]

array([2, 0, 1, 1, 0, 1, 2, 0, 2, 2, 2, 1, 0, 2, 1, 0, 1, 1, 2, 1, 2, 1,
       2, 1, 1, 1, 1, 2, 1, 2, 0, 1, 0, 2, 0, 2, 2, 2, 1, 1, 0, 2, 2, 0,
       2, 1, 0, 1, 2, 2, 2, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 2, 0, 1, 1, 2,
       2, 2, 2, 2, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2, 2, 2, 2, 0, 2, 2, 0,
       0, 1, 2, 0, 2, 2, 1, 1, 2, 2, 1, 2])

<h3> Training the model </h3>

In [ ]:
import tensorflow as tf 

In [ ]:
embedding_dim = 128
model = tf.keras.Sequential([
    # Add an Embedding layer expecting input vocab of size 5000, and output embedding dimension of size 64 we set at the top
    tf.keras.layers.Embedding(num_words, embedding_dim),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(embedding_dim)),
    #tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(32)),
    # use ReLU in place of tanh function since they are very good alternatives of each other.
    tf.keras.layers.Dense(embedding_dim, activation='relu'),
    # Add a Dense layer with 6 units and softmax activation.
    # When we have multiple outputs, softmax convert outputs layers into a probability distribution.
    tf.keras.layers.Dense(6, activation='softmax')
])
model.compile(
    loss = 'sparse_categorical_crossentropy',
    optimizer= 'adam',
    metrics= ['accuracy']
)
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, None, 128)         208512    
                                                                 
 bidirectional_2 (Bidirectio  (None, 256)              263168    
 nal)                                                            
                                                                 
 dense_4 (Dense)             (None, 128)               32896     
                                                                 
 dense_5 (Dense)             (None, 6)                 774       
                                                                 
Total params: 505,350
Trainable params: 505,350
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 64)          104256    
                                                                 
 bidirectional_1 (Bidirectio  (None, 128)              66048     
 nal)                                                            
                                                                 
 dense_2 (Dense)             (None, 64)                8256      
                                                                 
 dense_3 (Dense)             (None, 6)                 390       
                                                                 
Total params: 178,950
Trainable params: 178,950
Non-trainable params: 0
_________________________________________________________________


In [ ]:
History=model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test,y_test), verbose=2)

Epoch 1/10


InvalidArgumentError: ignored

In [ ]:
plt.figure(figsize=(15,5))
epochs = range(1, len(History.history['accuracy'])+1)
plt.plot(epochs, History.history['loss'], 'b', label='Training Loss', color='red')
plt.plot(epochs, History.history['val_loss'], 'b', label='Validation Loss')
plt.legend()
plt.show()

In [ ]:
validation_sentence = ['I will commit suicide']
validation_sentence_tockened = tokenizer.texts_to_sequences(validation_sentence)
validation_sentence_padded = pad_sequences(validation_sentence_tockened, maxlen=16, truncating ='post', padding='post')
print(validation_sentence[0])
print('Probablity of Suicide:{}'.format(model.predict(validation_sentence_padded)[0]))

In [ ]:
validation_sentence = ['I am really happy in my life ']
validation_sentence_tockened = tokenizer.texts_to_sequences(validation_sentence)
validation_sentence_padded = pad_sequences(validation_sentence_tockened, maxlen=16, truncating ='post', padding='post')
print(validation_sentence[0])
print('Probablity of Suicide:{}'.format(model.predict(validation_sentence_padded)[0]))